Hello pull request
Luchy-B/Microverse-Hello-Project pull request #1
Opened 2022-10-26 07:59 UTC by Luchy-B

Hello Microverse Pull Request

2022-10-26 08:48 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @Luchy-B  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great seup of linters. Linters are passing

Congrats on your work so far! :clap:  

## Required Changes ♻️

- [ ] Kindly add a readme following the microverse [readme template](https://github.com/microverseinc/readme-template/blob/master/README.md). A readme explains what your project is about to users, recruiters as well as reviewers.
Its also part of the project requirements 
<img width="1392" alt="Screenshot 2022-10-26 at 11 37 32" src="https://user-images.githubusercontent.com/48546992/197978751-0c0a4237-2003-4641-a334-0a3b0c7b74bb.png">

- [ ] I suggest you put a more descriptive pull request message. Its important to explain to a reviewer what you did in the pull request. An example here is highlight in bullet points what you did for the milestone. An example would be:
  - added a html file with Hello world
  - added a css file ...
  - added a .gitignore with ....
to edit the pull request description click on the three dots pointed to by the arrow on screenshot below
<img width="1562" alt="Screenshot 2022-10-26 at 11 43 55" src="https://user-images.githubusercontent.com/48546992/197979915-cf2d3cc9-7ab8-4df5-87ca-0504fc75487a.png">


There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

  
  
  ## OR TEMPLATE 2
Hi <STUDENT NAME>, 

Good job so far! 👏🏾 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Readme 
- Correct use of linters. which also pass.
- Github flow used
- .gitignore file added

## Required Changes ♻️
_Check the comments under the review._
- Please edit the title of your pull request. It should summarize what the pill request is about. Your current title  `[Megre Feature to Main branch](https://github.com/alexpuente0/Hello-microverse-cr/pull/1/)` is too general. Also it contains a typo.
- Your feature branch name does not follow the [Github flow rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md), the name should describe an action, 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 08:48 UTC, Nyame-Wolf commented on .gitignore
> +node_modules/
Kindly add the  `test.md` file to the .gitignore. Its part of the project requirements
<img width="1392" alt="Screenshot 2022-10-26 at 11 37 32" src="https://user-images.githubusercontent.com/48546992/197977577-81977d61-e35d-4a64-8444-99cd4c78afa4.png">

2022-10-26 15:39 UTC, Yazino12 commented
- Hi @Luchy-B, Please resolve the merge conflicts.
![image](https://user-images.githubusercontent.com/43172164/198071049-31e73de7-d537-4b66-b358-cbdc9acb06ac.png)
- This area should be green and the linter checks should be running. if you have any further questions reach out on slack **@Yasin Warsame**

2022-10-27 10:10 UTC, christianbiring1 approved these changes
Hi @Luchy-B , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![Iapproveokay](https://user-images.githubusercontent.com/97100091/198257084-00aea3de-ba22-45b7-b236-561bb18f4c97.gif)

## Highlights
- [ ] All linter checks are green :heavy_check_mark: 
- [ ] Good commit messages :+1: 
## Optional suggestions
- [ ] `I highly recommend you implement them for they take your project to the next level` :rocket: 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 10:10 UTC, christianbiring1 commented on README.md
[OPTIONAL] 
- [ ] Kindly make sure your project has a detailed description telling what the project is about for it's a core standard for a repo to be documented professionally.

2022-10-27 10:10 UTC, christianbiring1 commented on styles.css
> +  color: blue;
[OPTIONAL]
- [ ] Kindly make sure you select the element using a class and not the generic `HTML tag` as specified in the project requirement [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#:~:text=A%20.css%20file%20that%20includes%20one%20class%20with%20styles%20for%20your%20header%20(make%20it%20in%20your%20favorite%20color))

2022-10-27 10:34 UTC, merged